<a href="https://colab.research.google.com/github/Cursed-realm/Ecommerce-Sales-Customer-Analytics/blob/main/Ecommerce_Sales_Customer_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Day 1: Project Setup & Data Understanding
Set up the E-Commerce Analytics project, understood the business problem and dataset structure, and established the GitHub workflow

In [1]:
from google.colab import userdata
TOKEN = userdata.get('GITHUB_TOKEN')
USERNAME = "cursed-realm"
REPO_NAME = "Ecommerce-Sales-Customer-Analytics"
EMAIL = "adityasharmaagra2003@gmail.com"

!git config --global user.name "{USERNAME}"
!git config --global user.email "{EMAIL}"
!git clone "https://{USERNAME}:{TOKEN}@github.com/{USERNAME}/{REPO_NAME}.git"
%cd {REPO_NAME}

Cloning into 'Ecommerce-Sales-Customer-Analytics'...
remote: Enumerating objects: 31, done.
remote: Total 31 (delta 0), reused 0 (delta 0), pack-reused 31 (from 1)
Receiving objects: 100% (31/31), 53.12 MiB | 20.02 MiB/s, done.
Resolving deltas: 100% (12/12), done.
/content/Ecommerce-Sales-Customer-Analytics

In [2]:
import pandas as pd

customers = pd.read_csv("olist_customers_dataset.csv")
orders = pd.read_csv("olist_orders_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")
payments = pd.read_csv("olist_order_payments_dataset.csv")
reviews = pd.read_csv("olist_order_reviews_dataset.csv")
sellers = pd.read_csv("olist_sellers_dataset.csv")
geolocation = pd.read_csv("olist_geolocation_dataset.csv")
category_translation = pd.read_csv("product_category_name_translation.csv")

datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "products": products,
    "payments": payments,
    "reviews": reviews,
    "sellers": sellers,
    "geolocation": geolocation,
    "category_translation": category_translation
}

In [ ]:
for name, df in datasets.items():
    print(f"{name:22} → {df.shape[0]:,} rows × {df.shape[1]} columns")

customers              → 99,441 rows × 5 columns
orders                 → 99,441 rows × 8 columns
order_items            → 112,650 rows × 7 columns
products               → 32,951 rows × 9 columns
payments               → 103,886 rows × 5 columns
reviews                → 99,224 rows × 7 columns
sellers                → 3,095 rows × 4 columns
geolocation            → 1,000,163 rows × 5 columns
category_translation   → 71 rows × 2 columns

In [ ]:
for name, df in datasets.items():
    print(f"\n{name}")
    print(df.info())

customers
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB
None

orders
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB
None

order_items
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB
None

products
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB
None

payments
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB
None

reviews
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB
None

sellers
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB
None

geolocation
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB
None

category_translation
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB
None

In [ ]:
orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [ ]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   olist_customers_dataset.csv
	new file:   olist_geolocation_dataset.csv
	new file:   olist_order_items_dataset.csv
	new file:   olist_order_payments_dataset.csv
	new file:   olist_order_reviews_dataset.csv
	new file:   olist_orders_dataset.csv
	new file:   olist_products_dataset.csv
	new file:   olist_sellers_dataset.csv
	new file:   product_category_name_translation.csv

In [ ]:
!git add .

In [ ]:
!git commit -m "Day 1: loaded and explored Olist e-commerce dataset (9 tables), understood data grain, investigated missing delivery dates against order_status"

[main 9ec8ae5] Day 1: loaded and explored Olist e-commerce dataset (9 tables), understood data grain, investigated missing delivery dates against order_status
 9 files changed, 1556426 insertions(+)
 create mode 100644 olist_customers_dataset.csv
 create mode 100644 olist_geolocation_dataset.csv
 create mode 100644 olist_order_items_dataset.csv
 create mode 100644 olist_order_payments_dataset.csv
 create mode 100644 olist_order_reviews_dataset.csv
 create mode 100644 olist_orders_dataset.csv
 create mode 100644 olist_products_dataset.csv
 create mode 100644 olist_sellers_dataset.csv
 create mode 100644 product_category_name_translation.csv

In [ ]:
!git push

Enumerating objects: 12, done.
Counting objects: 100% (12/12), done.
Delta compression using up to 2 threads
Compressing objects: 100% (11/11), done.
Writing objects: 100% (11/11), 42.32 MiB | 4.28 MiB/s, done.
Total 11 (delta 0), reused 0 (delta 0), pack-reused 0
remote: warning: See https://gh.io/lfs for more information.
remote: warning: File olist_geolocation_dataset.csv is 58.44 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: This repository moved. Please use the new location:
remote:   https://github.com/Cursed-realm/Ecommerce-Sales-Customer-Analytics.git
To https://github.com/cursed-realm/Ecommerce-Sales-Customer-Analytics.git
   7515cff..9ec8ae5  main -> main

## Day 2: Data Cleaning & Data Quality
Investigated missing values in products, checked for duplicates across all tables, and converted date columns to proper datetime format

In [ ]:
missing = products.isnull().sum()
missing = missing[missing > 0].sort_values(ascending=False)
print(missing)
print("\nTotal rows in products:", len(products))
print("\n% missing per column:")
print((missing / len(products) * 100).round(2))

product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

Total rows in products: 32951

% missing per column:
product_category_name         1.85
product_name_lenght           1.85
product_description_lenght    1.85
product_photos_qty            1.85
product_weight_g              0.01
product_length_cm             0.01
product_height_cm             0.01
product_width_cm              0.01
dtype: float64

In [ ]:
missing_category = products[products['product_category_name'].isnull()]
missing_category.head(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
244,e10758160da97891c2fdcbc35f0f031d,NaN,NaN,NaN,NaN,2200.0,16.0,2.0,11.0
294,39e3b9b12cd0bf8ee681bbc1c130feb5,NaN,NaN,NaN,NaN,300.0,16.0,7.0,11.0
299,794de06c32a626a5692ff50e4985d36f,NaN,NaN,NaN,NaN,300.0,18.0,8.0,14.0
347,7af3e2da474486a3519b0cba9dea8ad9,NaN,NaN,NaN,NaN,200.0,22.0,14.0,14.0
428,629beb8e7317703dcc5f35b5463fd20e,NaN,NaN,NaN,NaN,1400.0,25.0,25.0,25.0

In [ ]:
products[missing.index].isnull().sum(axis=1).value_counts().sort_index()

0    32340
4      610
8        1
Name: count, dtype: int64

In [ ]:
missing_counts = products[missing.index].isnull().sum(axis=1)
products[missing_counts == 8]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
dims_missing = products[products['product_weight_g'].isnull()]
dims_missing

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
edge_case_ids = ['09ff539a621711667c43eba6a3bd8466', '5eb564652db742ff8f28759cd8d2652a']
order_items[order_items['product_id'].isin(edge_case_ids)]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
7098,101157d4fae1c9fb74a00a5dee265c25,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-11 08:02:26,29.0,14.52
9233,1521c6bb7b1028154c8c67cf80fa809f,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-07 10:10:16,29.0,16.05
28715,415cfaaaa8cea49f934470548797fed1,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-07 10:35:19,29.0,14.52
28716,415cfaaaa8cea49f934470548797fed1,2,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-07 10:35:19,29.0,14.52
39299,595316a07cd3dea9db7adfcc7e247ae7,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-08-18 04:26:04,39.0,9.27
48424,6e150190fbe04c642a9cf0b80d83ee16,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-06-30 16:45:14,39.0,16.79
48980,6f497c40431d5fb0cfbd6c943dd29215,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-11 05:55:32,29.0,10.96
58833,85f8ad45e067abd694b627859fa57453,1,09ff539a621711667c43eba6a3bd8466,8b8cfc8305aa441e4239358c9f6f2485,2017-02-03 21:40:02,1934.0,27.00
71134,a2456e7f02197951664897a94c87242d,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-06 11:50:09,29.0,24.84
73556,a7a43f469c0d7bdb0a23a82db125aefa,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-08-28 13:15:11,39.0,15.10
82767,bbfc7badbed2f1828e22b6d629201bd4,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-07-18 04:04:10,39.0,11.85
84199,bf49f84a0580ef6751e13357776b7ed9,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-07-09 21:35:18,39.0,15.10
85060,c1424efcde3c9e9febd9e1761667789e,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-14 02:45:36,29.0,14.52
93346,d38dcb503cd4ddc6ce7702552918bd8f,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-06-09 17:55:13,39.0,15.10
93347,d38dcb503cd4ddc6ce7702552918bd8f,2,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-06-09 17:55:13,39.0,15.10
97847,ddf16d77e858a32f36e10c289a28ef61,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-05-02 10:50:08,29.0,14.52
100495,e3daea0200104991cb979c2fcc509ae7,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-06 14:22:36,29.0,10.96
103715,eb855beb3ac99461f7a076b4c3652472,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-03-30 16:03:46,29.0,14.52

In [ ]:
products['product_category_name'] = products['product_category_name'].fillna('unknown')
products['product_photos_qty'] = products['product_photos_qty'].fillna(0)

In [ ]:
bebes_median = products[products['product_category_name'] == 'bebes'][
    ['product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']
].median()

print(bebes_median)

product_weight_g     850.0
product_length_cm     33.0
product_height_cm     16.0
product_width_cm      25.0
dtype: float64

In [ ]:
mask_8578 = products['product_id'] == '09ff539a621711667c43eba6a3bd8466'

for col in ['product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']:
    products.loc[mask_8578, col] = products.loc[mask_8578, col].fillna(bebes_median[col])

In [ ]:
overall_median = products[
    ['product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']
].median()

print(overall_median)

product_weight_g     700.0
product_length_cm     25.0
product_height_cm     13.0
product_width_cm      20.0
dtype: float64

In [ ]:
mask_18851 = products['product_id'] == '5eb564652db742ff8f28759cd8d2652a'

for col in ['product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']:
    products.loc[mask_18851, col] = products.loc[mask_18851, col].fillna(overall_median[col])

In [ ]:
print(products.isnull().sum())

product_id                      0
product_category_name           0
product_name_lenght           610
product_description_lenght    610
product_photos_qty              0
product_weight_g                0
product_length_cm               0
product_height_cm               0
product_width_cm                0
dtype: int64

In [ ]:
for name, df in datasets.items():
    dupes = df.duplicated().sum()
    print(f"{name}: {dupes} exact duplicate rows")

customers: 0 exact duplicate rows
orders: 0 exact duplicate rows
order_items: 0 exact duplicate rows
products: 0 exact duplicate rows
payments: 0 exact duplicate rows
reviews: 0 exact duplicate rows
sellers: 0 exact duplicate rows
geolocation: 261831 exact duplicate rows
category_translation: 0 exact duplicate rows

In [ ]:
geolocation[geolocation.duplicated(keep=False)].sort_values('geolocation_zip_code_prefix').head(15)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
851,1001,-23.549825,-46.633970,sao paulo,SP
1062,1001,-23.550498,-46.634338,sao paulo,SP
1246,1001,-23.549292,-46.633559,sao paulo,SP
897,1001,-23.549292,-46.633559,sao paulo,SP
99,1001,-23.549292,-46.633559,sao paulo,SP
864,1001,-23.549825,-46.633970,sao paulo,SP
771,1001,-23.550498,-46.634338,sao paulo,SP
818,1001,-23.551337,-46.634027,sao paulo,SP
1384,1001,-23.549292,-46.633559,sao paulo,SP
429,1001,-23.550498,-46.634338,sao paulo,SP
583,1001,-23.551337,-46.634027,sao paulo,SP
519,1001,-23.551337,-46.634027,sao paulo,SP
639,1001,-23.550498,-46.634338,sao paulo,SP
1004,1001,-23.549292,-46.633559,sao paulo,SP
985,1001,-23.550498,-46.634338,sao paulo,SP

In [ ]:
print("Before:", len(geolocation))
print("After dropping exact duplicates:", len(geolocation.drop_duplicates()))
print("Unique zip code prefixes:", geolocation['geolocation_zip_code_prefix'].nunique())

Before: 1000163
After dropping exact duplicates: 738332
Unique zip code prefixes: 19015

In [ ]:
geolocation = geolocation.drop_duplicates().reset_index(drop=True)
print("Rows after dropping exact duplicates:", len(geolocation))

Rows after dropping exact duplicates: 738332

In [ ]:
geolocation_agg = geolocation.groupby('geolocation_zip_code_prefix').agg({
    'geolocation_lat': 'mean',
    'geolocation_lng': 'mean',
    'geolocation_city': lambda x: x.mode()[0],   # most frequent city for that prefix
    'geolocation_state': lambda x: x.mode()[0]   # most frequent state for that prefix
}).reset_index()

print("Rows after collapsing to one per zip prefix:", len(geolocation_agg))
geolocation_agg.head()

Rows after collapsing to one per zip prefix: 19015

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1001,-23.550227,-46.634039,sao paulo,SP
1,1002,-23.547657,-46.634991,sao paulo,SP
2,1003,-23.549000,-46.635582,sao paulo,SP
3,1004,-23.549829,-46.634792,sao paulo,SP
4,1005,-23.549547,-46.636406,sao paulo,SP

In [ ]:
for name, df in datasets.items():
    date_cols = [col for col in df.columns if 'date' in col.lower() or 'timestamp' in col.lower()]
    if date_cols:
        print(f"{name}: {date_cols}")

orders: ['order_purchase_timestamp', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
order_items: ['shipping_limit_date']
reviews: ['review_creation_date', 'review_answer_timestamp']

In [ ]:
orders.columns.tolist()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date']

In [ ]:
orders_date_cols = ['order_purchase_timestamp', 'order_approved_at',
                     'order_delivered_carrier_date', 'order_delivered_customer_date',
                     'order_estimated_delivery_date']
for col in orders_date_cols:
    orders[col] = pd.to_datetime(orders[col])

order_items['shipping_limit_date'] = pd.to_datetime(order_items['shipping_limit_date'])

reviews_date_cols = ['review_creation_date', 'review_answer_timestamp']
for col in reviews_date_cols:
    reviews[col] = pd.to_datetime(reviews[col])

print("orders dtypes:\n", orders[orders_date_cols].dtypes)
print("\norder_items dtype:\n", order_items[['shipping_limit_date']].dtypes)
print("\nreviews dtypes:\n", reviews[reviews_date_cols].dtypes)

orders dtypes:
 order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

order_items dtype:
 shipping_limit_date    datetime64[ns]
dtype: object

reviews dtypes:
 review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

In [ ]:
print(orders[orders_date_cols].dtypes)
print(order_items[['shipping_limit_date']].dtypes)
print(reviews[reviews_date_cols].dtypes)

order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object
shipping_limit_date    datetime64[ns]
dtype: object
review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

In [ ]:
customers.to_csv("olist_customers_dataset.csv", index=False)
orders.to_csv("olist_orders_dataset.csv", index=False)
order_items.to_csv("olist_order_items_dataset.csv", index=False)
products.to_csv("olist_products_dataset.csv", index=False)
payments.to_csv("olist_order_payments_dataset.csv", index=False)
reviews.to_csv("olist_order_reviews_dataset.csv", index=False)
sellers.to_csv("olist_sellers_dataset.csv", index=False)
geolocation_agg.to_csv("olist_geolocation_dataset.csv", index=False)
category_translation.to_csv("product_category_name_translation.csv", index=False)

In [ ]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   olist_customers_dataset.csv
	modified:   olist_geolocation_dataset.csv
	modified:   olist_order_items_dataset.csv
	modified:   olist_order_payments_dataset.csv
	modified:   olist_order_reviews_dataset.csv
	modified:   olist_orders_dataset.csv
	modified:   olist_products_dataset.csv
	modified:   olist_sellers_dataset.csv
	modified:   product_category_name_translation.csv

no changes added to commit (use "git add" and/or "git commit -a")

In [ ]:
!git add .

In [ ]:
!git commit -m "Day 2: Clean missing values, remove duplicates, convert date columns to datetime"

[main 7172078] Day 2: Clean missing values, remove duplicates, convert date columns to datetime
 9 files changed, 538893 insertions(+), 1520041 deletions(-)
 rewrite olist_geolocation_dataset.csv (98%)
 rewrite olist_products_dataset.csv (70%)
 rewrite olist_sellers_dataset.csv (97%)

In [ ]:
!git push

Enumerating objects: 18, done.
Counting objects: 100% (18/18), done.
Delta compression using up to 2 threads
Compressing objects: 100% (11/11), done.
Writing objects: 100% (11/11), 13.70 MiB | 2.52 MiB/s, done.
Total 11 (delta 6), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (6/6), completed with 6 local objects.
remote: This repository moved. Please use the new location:
remote:   https://github.com/Cursed-realm/Ecommerce-Sales-Customer-Analytics.git
To https://github.com/cursed-realm/Ecommerce-Sales-Customer-Analytics.git
   ff8e3bf..7172078  main -> main

In [4]:
import pandas as pd

orders = pd.read_csv("olist_orders_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")

print("Orders dtypes:")
print(orders.dtypes)
print("\nOrders missing values:")
print(orders.isnull().sum())
print("\nProducts missing values:")
print(products.isnull().sum())
print("\nDuplicate rows in orders:", orders.duplicated().sum())

Orders dtypes:
order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

Orders missing values:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Products missing values:
product_id                      0
product_category_name           0
product_name_lenght           610
product_description_lenght    610
product_photos_qty              0
product_weight_g                0
product_length_cm               0
product_height_cm               0
product_width_cm                0
dtype: int64

Duplicate rows in orders: 0

In [5]:
date_cols = ['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date',
             'order_delivered_customer_date', 'order_estimated_delivery_date']

for col in date_cols:
    orders[col] = pd.to_datetime(orders[col])

orders.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [6]:
products[['product_name_lenght', 'product_description_lenght']] = products[['product_name_lenght', 'product_description_lenght']].fillna(0)
products.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [7]:
orders.to_csv("olist_orders_dataset.csv", index=False)
products.to_csv("olist_products_dataset.csv", index=False)

## Day 3: SQL Fundamentals - Database Setup & Basic Queries
Loaded cleaned data into a SQLite database and wrote SQL queries (SELECT, WHERE, JOINs) to answer business questions

In [8]:
import sqlite3

conn = sqlite3.connect('ecommerce.db')

customers.to_sql('customers', conn, if_exists='replace', index=False)
orders.to_sql('orders', conn, if_exists='replace', index=False)
order_items.to_sql('order_items', conn, if_exists='replace', index=False)
products.to_sql('products', conn, if_exists='replace', index=False)
payments.to_sql('payments', conn, if_exists='replace', index=False)
sellers.to_sql('sellers', conn, if_exists='replace', index=False)

3095

In [10]:
query = """
SELECT order_id, order_status, order_purchase_timestamp
FROM orders
LIMIT 5;
"""

pd.read_sql(query, conn)

                           order_id order_status order_purchase_timestamp
0  e481f51cbdc54678b7cc49136f2d6af7    delivered      2017-10-02 10:56:33
1  53cdb2fc8bc7dce0b6741e2150273451    delivered      2018-07-24 20:41:37
2  47770eb9100c2d0c44946d9cf07ec65d    delivered      2018-08-08 08:38:49
3  949d5b44dbf5de918fe9c16f97b45f8a    delivered      2017-11-18 19:28:06
4  ad21c59c0840e6cb83a9ceb5573f8159    delivered      2018-02-13 21:18:39

In [11]:
query = """
SELECT order_status, COUNT(*) as order_count
FROM orders
GROUP BY order_status
ORDER BY order_count DESC;
"""

pd.read_sql(query, conn)

  order_status  order_count
0    delivered        96478
1      shipped         1107
2     canceled          625
3  unavailable          609
4     invoiced          314
5   processing          301
6      created            5
7     approved            2

In [12]:
query = """
SELECT o.order_id, o.order_status, c.customer_city, c.customer_state
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
LIMIT 10;
"""

pd.read_sql(query, conn)

,order_id,order_status,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,delivered,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,delivered,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,delivered,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,delivered,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,delivered,santo andre,SP
5,a4591c265e18cb1dcee52889e2d8acc3,delivered,congonhinhas,PR
6,136cce7faa42fdb2cefd53fdc79a6098,invoiced,santa rosa,RS
7,6514b8ad8028c9f2cc2374ded245783f,delivered,nilopolis,RJ
8,76c6e866289321a7c93b82b54852dc33,delivered,faxinalzinho,RS
9,e69bfb5eb88e0ed6a785585b27e16dbf,delivered,sorocaba,SP

In [13]:
query = """
SELECT p.product_category_name,
       COUNT(oi.order_id) as items_sold,
       ROUND(SUM(oi.price), 2) as total_revenue
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_category_name
ORDER BY total_revenue DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

    product_category_name  items_sold  total_revenue
0            beleza_saude        9670     1258681.34
1      relogios_presentes        5991     1205005.68
2         cama_mesa_banho       11115     1036988.68
3           esporte_lazer        8641      988048.97
4  informatica_acessorios        7827      911954.32
5        moveis_decoracao        8334      729762.49
6              cool_stuff        3796      635290.85
7   utilidades_domesticas        6964      632248.66
8              automotivo        4235      592720.11
9      ferramentas_jardim        4347      485256.46

In [17]:
category_translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [18]:
category_translation.to_sql('category_translation', conn, if_exists='replace', index=False)

71

In [19]:
query = """
SELECT ct.product_category_name_english,
       COUNT(oi.order_id) as items_sold,
       ROUND(SUM(oi.price), 2) as total_revenue
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
JOIN category_translation ct ON p.product_category_name = ct.product_category_name
GROUP BY ct.product_category_name_english
ORDER BY total_revenue DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

  product_category_name_english  items_sold  total_revenue
0                 health_beauty        9670     1258681.34
1                 watches_gifts        5991     1205005.68
2                bed_bath_table       11115     1036988.68
3                sports_leisure        8641      988048.97
4         computers_accessories        7827      911954.32
5               furniture_decor        8334      729762.49
6                    cool_stuff        3796      635290.85
7                    housewares        6964      632248.66
8                          auto        4235      592720.11
9                  garden_tools        4347      485256.46

In [20]:
query = """
SELECT c.customer_state, COUNT(DISTINCT o.order_id) as total_orders
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_state
ORDER BY total_orders DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

  customer_state  total_orders
0             SP         41746
1             RJ         12852
2             MG         11635
3             RS          5466
4             PR          5045
5             SC          3637
6             BA          3380
7             DF          2140
8             ES          2033
9             GO          2020

In [30]:
products.to_csv("olist_products_dataset.csv", index=False)

In [31]:
! git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [23]:
!git add .

In [24]:
!git commit -m "Day 2 fix + Day 3: converted date columns, filled missing product metadata, built SQLite database with JOIN queries (category revenue, customer geography)"

[main 307a2fc] Day 2 fix + Day 3: converted date columns, filled missing product metadata, built SQLite database with JOIN queries (category revenue, customer geography)
 2 files changed, 610 insertions(+), 610 deletions(-)
 create mode 100644 ecommerce.db

In [25]:
!git push

Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 2 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 23.76 MiB | 5.88 MiB/s, done.
Total 4 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: warning: See https://gh.io/lfs for more information.
remote: warning: File ecommerce.db is 50.85 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: This repository moved. Please use the new location:
remote:   https://github.com/Cursed-realm/Ecommerce-Sales-Customer-Analytics.git
To https://github.com/cursed-realm/Ecommerce-Sales-Customer-Analytics.git
   071a4c9..307a2fc  main -> main

In [26]:
import pandas as pd
orders_check = pd.read_csv("olist_orders_dataset.csv")
orders_check.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [32]:
import pandas as pd

orders = pd.read_csv("olist_orders_dataset.csv")

date_cols = ['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date',
             'order_delivered_customer_date', 'order_estimated_delivery_date']

for col in date_cols:
    orders[col] = pd.to_datetime(orders[col])

orders.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

## Day 4: SQL - CTEs & Window Functions
Used CTEs and window functions to identify top customers by spending and rank states by revenue

In [34]:
query = """
WITH customer_spending AS (
    SELECT o.customer_id, SUM(p.payment_value) as total_spent
    FROM orders o
    JOIN payments p ON o.order_id = p.order_id
    GROUP BY o.customer_id
)
SELECT customer_id, total_spent
FROM customer_spending
ORDER BY total_spent DESC
LIMIT 10;
"""
pd.read_sql(query, conn)

                        customer_id  total_spent
0  1617b1357756262bfa56ab541c47bc16     13664.08
1  ec5b2ba62e574342386871631fafd3fc      7274.88
2  c6e2731c5b391845f6800c97401a43a9      6929.31
3  f48d464a0baaea338cb25f816991ab1f      6922.21
4  3fd6777bbce08a352fddd04e4a7cc8f6      6726.66
5  05455dfa7cd02f13d132aa7a6a9729c6      6081.54
6  df55c14d1476a9a3467f131269c2477f      4950.34
7  e0a2412720e9ea4f26c1ac985f6a7358      4809.44
8  24bbf5fd2f2e1b359ee7de94defc4a15      4764.34
9  3d979689f636322c62418b6346b1c6d2      4681.78

In [35]:
query = """
SELECT c.customer_state,
       ROUND(SUM(p.payment_value), 2) as state_revenue,
       RANK() OVER (ORDER BY SUM(p.payment_value) DESC) as revenue_rank
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN payments p ON o.order_id = p.order_id
GROUP BY c.customer_state
ORDER BY revenue_rank
LIMIT 10;
"""
pd.read_sql(query, conn)

  customer_state  state_revenue  revenue_rank
0             SP     5998226.96             1
1             RJ     2144379.69             2
2             MG     1872257.26             3
3             RS      890898.54             4
4             PR      811156.38             5
5             SC      623086.43             6
6             BA      616645.82             7
7             DF      355141.08             8
8             GO      350092.31             9
9             ES      325967.55            10

In [36]:
query = """
WITH monthly_revenue AS (
    SELECT strftime('%Y-%m', o.order_purchase_timestamp) as month,
           ROUND(SUM(p.payment_value), 2) as revenue
    FROM orders o
    JOIN payments p ON o.order_id = p.order_id
    GROUP BY month
)
SELECT month, revenue,
       ROUND(SUM(revenue) OVER (ORDER BY month), 2) as running_total
FROM monthly_revenue
ORDER BY month;
"""
pd.read_sql(query, conn)

      month     revenue  running_total
0   2016-09      252.24         252.24
1   2016-10    59090.48       59342.72
2   2016-12       19.62       59362.34
3   2017-01   138488.04      197850.38
4   2017-02   291908.01      489758.39
5   2017-03   449863.60      939621.99
6   2017-04   417788.03     1357410.02
7   2017-05   592918.82     1950328.84
8   2017-06   511276.38     2461605.22
9   2017-07   592382.92     3053988.14
10  2017-08   674396.32     3728384.46
11  2017-09   727762.45     4456146.91
12  2017-10   779677.88     5235824.79
13  2017-11  1194882.80     6430707.59
14  2017-12   878401.48     7309109.07
15  2018-01  1115004.18     8424113.25
16  2018-02   992463.34     9416576.59
17  2018-03  1159652.12    10576228.71
18  2018-04  1160785.48    11737014.19
19  2018-05  1153982.15    12890996.34
20  2018-06  1023880.50    13914876.84
21  2018-07  1066540.75    14981417.59
22  2018-08  1022425.32    16003842.91
23  2018-09     4439.54    16008282.45
24  2018-10      589.67    16008872.12

In [37]:
query = """
SELECT strftime('%Y-%m', order_purchase_timestamp) as month, COUNT(*) as order_count
FROM orders
GROUP BY month
ORDER BY month;
"""
pd.read_sql(query, conn)

      month  order_count
0   2016-09            4
1   2016-10          324
2   2016-12            1
3   2017-01          800
4   2017-02         1780
5   2017-03         2682
6   2017-04         2404
7   2017-05         3700
8   2017-06         3245
9   2017-07         4026
10  2017-08         4331
11  2017-09         4285
12  2017-10         4631
13  2017-11         7544
14  2017-12         5673
15  2018-01         7269
16  2018-02         6728
17  2018-03         7211
18  2018-04         6939
19  2018-05         6873
20  2018-06         6167
21  2018-07         6292
22  2018-08         6512
23  2018-09           16
24  2018-10            4

In [38]:
query = """
WITH monthly_revenue AS (
    SELECT strftime('%Y-%m', o.order_purchase_timestamp) as month,
           ROUND(SUM(p.payment_value), 2) as revenue
    FROM orders o
    JOIN payments p ON o.order_id = p.order_id
    WHERE strftime('%Y-%m', o.order_purchase_timestamp) NOT IN ('2016-09', '2016-12', '2018-09', '2018-10')
    GROUP BY month
)
SELECT month, revenue,
       ROUND(SUM(revenue) OVER (ORDER BY month), 2) as running_total
FROM monthly_revenue
ORDER BY month;
"""
pd.read_sql(query, conn)

      month     revenue  running_total
0   2016-10    59090.48       59090.48
1   2017-01   138488.04      197578.52
2   2017-02   291908.01      489486.53
3   2017-03   449863.60      939350.13
4   2017-04   417788.03     1357138.16
5   2017-05   592918.82     1950056.98
6   2017-06   511276.38     2461333.36
7   2017-07   592382.92     3053716.28
8   2017-08   674396.32     3728112.60
9   2017-09   727762.45     4455875.05
10  2017-10   779677.88     5235552.93
11  2017-11  1194882.80     6430435.73
12  2017-12   878401.48     7308837.21
13  2018-01  1115004.18     8423841.39
14  2018-02   992463.34     9416304.73
15  2018-03  1159652.12    10575956.85
16  2018-04  1160785.48    11736742.33
17  2018-05  1153982.15    12890724.48
18  2018-06  1023880.50    13914604.98
19  2018-07  1066540.75    14981145.73
20  2018-08  1022425.32    16003571.05

In [39]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean